includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  For information on how to proceed, see https://wiki.openstack.org/wiki/GerritJenkinsGit#Test_Failures
    manager: IndependentPipelineManager
    precedence: low
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
#    start:
#      gerrit:
#        verified: 0
#    success:
#      gerrit:
#        verified: 1
#    failure:
#      gerrit:
#        verified: -1

jobs:
  - name: ^.*$
    parameter-function: single_use_node

projects:

  # everytime this changes, run a test!
  - name: stackforge/puppet-openstack_dev_env
    check:
      - gate-puppet-integration
