includes:
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: Build failed.  For information on how to proceed, see https://wiki.openstack.org/wiki/GerritJenkinsGit#Test_Failures
    manager: IndependentPipelineManager
    precedence: low
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: patchset-created
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1

  - name: gate
    description: Changes that have been approved by core developers are enqueued in order in this pipeline, and if they pass tests in Jenkins, will be merged.
    failure-message: Build failed.  For information on how to proceed, see https://wiki.openstack.org/wiki/GerritJenkinsGit#Test_Failures
    manager: DependentPipelineManager
    precedence: normal
    require:
      open: True
      current-patchset: True
    trigger:
      gerrit:
        - event: comment-added
          require-approval:
            - verified: 1
              username: jenkins
              newer-than: 24h
          approval:
            - workflow: 1
        - event: comment-added
          require-approval:
            - verified: 2
              username: jenkins
              newer-than: 24h
          approval:
            - workflow: 1
        - event: comment-added
          approval:
            - verified: 1
          username_filter: jenkins
    start:
      gerrit:
        verified: 0
    success:
      gerrit:
        verified: 2
        submit: true
    failure:
      gerrit:
        verified: -2
    window-floor: 20
    window-increase-factor: 2

#  - name: post
#    description: This pipeline runs jobs that operate after each change is merged.
#    manager: IndependentPipelineManager
#    precedence: low
#    trigger:
#      gerrit:
#        - event: ref-updated
#          ref: ^(?!(devnull|refs/.*)).*$


#project-templates:
#  - name: python-jobs
#    check:
#      - 'gate-{name}-pep8'
#      - 'gate-{name}-docs'
#      - 'gate-{name}-python26'
#      - 'gate-{name}-python27'
#    gate:
#      - 'gate-{name}-docs'
#      - 'gate-{name}-pep8'
#      - 'gate-{name}-python26'
#      - 'gate-{name}-python27'
#    post:
#      - '{name}-branch-tarball'
#      - '{name}-coverage'

jobs:
  - name: ^.*$
    parameter-function: single_use_node

# The project list is grouped by type of project, and within each
# group, projects are sorted (mostly) alphabetically.
projects:

# Section: OpenStack server projects

  - name: openstack-dev/sandbox
    check:
       - puppet-glance-3.6-unit 
#    gate:
#       - foo
#    post:
#      - noop

  - name: stackforge/puppet-openstack_dev_env
    check:
      - bar
